---
# file: oracle-java/tasks/redhat/main.yml
#
# Task file to install Oracle Java Development Kit in a system with a Redhat based Linux distribution.
#

- name: get latest JDK download page
  uri:
    url: http://www.oracle.com/technetwork/java/javase/downloads/index.html
    return_content: yes
  register: result

- name: determine latest java download page and version
  set_fact: latest_java_page_and_version="{{ (result.content.replace('\n','')|regex_replace('.*(/technetwork/java/javase/downloads/jdk(\d+)-downloads.*?.html).*', 'http://www.oracle.com/\1\n\2')).split('\n') }}"

- name: define download page URL based on latest version
  set_fact: download_page_url="{{ latest_java_page_and_version[0] }}"
  when: "{{ latest_java_page_and_version[1]|version_compare(oracle_java_version,'=') }}"
  
- block:
  
  - name: get lastest JDK rpm url
    uri: url="{{ result.content.replace('\n','')|regex_replace('.*(/technetwork/java/javase/archive-.*?.html).*','http://www.oracle.com/\1') }}"
         return_content=yes
    register: result
    
  - name: define download page URL for "{{ oracle_java_version }}"
    set_fact: download_page_url="{{ result.content|regex_search('href=\"[^\"]+\">Java SE\s+' + (oracle_java_version|string) + '\s?<')|regex_replace('.*href=\"([^\"]+)\".*','http://www.oracle.com/\1') }}"
  
  when: "{{ latest_java_page_and_version[1]|version_compare(oracle_java_version,'!=') and oracle_java_version }}"

- name: show download page URL
  debug: msg="{{ download_page_url }}"

- name: get lastest JDK rpm url
  uri: url="{{ download_page_url }}"
       return_content=yes
  register: result

- name: set oracle_java_rpm_url
  set_fact: oracle_java_rpm_url="{{ result.content|regex_search('https?://download.oracle.com/.*?/jdk-\w+-linux-' + oracle_java_ansible_arch_mappings[ansible_architecture] + '.rpm') }}"

- name: set some variables
  set_fact: oracle_java_rpm_filename="{{ oracle_java_rpm_url | basename }}"
            oracle_java_version="{{ oracle_java_rpm_url | basename|regex_replace('jdk-(\d+)u(\d+)-linux.*','\1') }}"
            oracle_java_version_update="{{ oracle_java_rpm_url | basename|regex_replace('jdk-(\d+)u(\d+)-linux.*','\2') }}"

- debug: msg="Downloading java {{ oracle_java_version }}u{{ oracle_java_version_update }} to {{ oracle_java_rpm_filename }} from {{ oracle_java_rpm_url }}"

- name: download Java RPM
  get_url:
    headers='Cookie:oraclelicense=accept-securebackup-cookie;OHS-edelivery.oracle.com-443=C7F18BF5F2D4EB3C9213441836A6CEFC8369EB725131A623DD4EE916516BCEAE02049760D8D3D6A6F6191D2D0BBF4CBCE87FACD030D15E809BD2F4B0E4734357F6044819781B9BE22172E9ECC5C202481FAC128F3086F6F255734D64A167A2C1CEB92C50E2D6DDB2B51FC8A971033A6B8CA72C6713C4800F6F4C6DE069B09D10C2B6E3C6472CA328AB7BCB7FFC37478F1485B856246888D400699202DAF7DDD16E2DAD0ADB91DD3A7075E3C8B993DB431AC79C51CFF92F589FF043C3B63AE5AA6F84395D8A4A03778C92C9D996F790869C27C7CE45777B89F71251FFEA0FB6DEBAFF6EE711331957~' dest="{{ oracle_java_dir_source }}/{{ oracle_java_rpm_filename }}" url="{{ oracle_java_rpm_url }}" validate_certs="{{ oracle_java_rpm_validate_certs }}" timeout={{ oracle_java_download_timeout }}
  register: oracle_java_task_rpm_download
  become: yes
  tags: [ installation ]

- name: install RPM
  action: "{{ ansible_pkg_mgr }} name={{ oracle_java_dir_source }}/{{ oracle_java_rpm_filename }} state=present"
  when: not oracle_java_task_rpm_download|skipped
  become: yes
  tags: [ installation ]

- name: set Java version as default
  alternatives:
    name="{{ item.exe }}"
    link="/usr/bin/{{ item.exe }}"
    path="{{ item.path }}/{{ item.exe }}"
  with_items:
    - { path: "{{ oracle_java_home }}/jre/bin", exe: 'java' }
    - { path: "{{ oracle_java_home }}/jre/bin", exe: 'keytool' }
    - { path: "{{ oracle_java_home }}/bin", exe: 'javac' }
    - { path: "{{ oracle_java_home }}/bin", exe: 'javadoc' }
  become: yes
  when: (
          oracle_java_set_as_default and
          oracle_java_task_rpm_download is defined and
          oracle_java_task_rpm_download|changed
        ) or (
          oracle_java_set_as_default and
          oracle_java_installed is defined and
          oracle_java_installed and
          oracle_java_version_installed is defined and
          oracle_java_version_installed != oracle_java_version_string)
  register: oracle_java_task_set_default

- name: in case there were changes, check host environment again
  include: ../check_environment.yml
  when: (
          oracle_java_task_rpm_download is defined and
          not oracle_java_task_rpm_download|skipped
        ) or (
          oracle_java_task_set_default is defined and
          oracle_java_task_set_default|changed
        )
